// backend/src/common/constants/error-codes.ts

export const ErrorCodes = {
  DUPLICATE_REGISTRATION: 'DUPLICATE_REGISTRATION',
  WEBINAR_NOT_FOUND: 'WEBINAR_NOT_FOUND',
  INVALID_WEBINAR_ID: 'INVALID_WEBINAR_ID',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
};
